title: dcrossleyau.github.io
description: >
  This is a test.
baseurl: ""
url: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
