title: dcrossleyau.github.io
description: >
  This is a test.
baseurl: ""
url: "https://dcrossleyau.github.io"

# Build settings
remote_theme: Balancingrock/classic-jekyll-theme
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
